const mongoose = require('mongoose');

const complianceReportSchema = new mongoose.Schema({
  // Report identification
  reportId: {
    type: String,
    required: true,
    unique: true
  },
  
  // Report metadata
  reportType: {
    type: String,
    required: true,
    enum: [
      'GDPR_COMPLIANCE', 'HIPAA_COMPLIANCE', 'SOX_COMPLIANCE', 'PCI_COMPLIANCE',
      'SECURITY_ASSESSMENT', 'PRIVACY_AUDIT', 'ACCESS_REVIEW', 'DATA_RETENTION',
      'REGULATORY_COMPLIANCE', 'CUSTOM_COMPLIANCE'
    ]
  },
  
  // Report period
  period: {
    startDate: {
      type: Date,
      required: true
    },
    endDate: {
      type: Date,
      required: true
    }
  },
  
  // Report scope
  scope: {
    type: [String], // List of systems, modules, or data types covered
    default: []
  },
  
  // Compliance status
  status: {
    overall: {
      type: String,
      enum: ['COMPLIANT', 'NON_COMPLIANT', 'PARTIALLY_COMPLIANT', 'PENDING_REVIEW'],
      default: 'PENDING_REVIEW'
    },
    findings: [{
      category: {
        type: String,
        required: true
      },
      severity: {
        type: String,
        enum: ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO'],
        required: true
      },
      description: {
        type: String,
        required: true
      },
      evidence: {
        type: [String],
        default: []
      },
      recommendation: String,
      status: {
        type: String,
        enum: ['OPEN', 'IN_PROGRESS', 'RESOLVED', 'WONT_FIX'],
        default: 'OPEN'
      },
      assignedTo: String,
      dueDate: Date
    }]
  },
  
  // Regulatory requirements mapping
  requirements: [{
    standard: {
      type: String,
      enum: ['GDPR', 'HIPAA', 'SOX', 'PCI_DSS', 'ISO_27001', 'NIST_CSF', 'OTHER'],
      required: true
    },
    requirementId: String,
    description: String,
    status: {
      type: String,
      enum: ['MET', 'NOT_MET', 'PARTIALLY_MET', 'NOT_APPLICABLE'],
      default: 'NOT_APPLICABLE'
    },
    evidence: [String],
    lastAssessed: Date
  }],
  
  // Metrics and statistics
  metrics: {
    totalEvents: Number,
    securityEvents: Number,
    privacyEvents: Number,
    complianceEvents: Number,
    violations: Number,
    remediations: Number,
    riskScore: {
      type: Number,
      min: 0,
      max: 100
    }
  },
  
  // Generated by
  generatedBy: {
    userId: String,
    userName: String,
    timestamp: {
      type: Date,
      default: Date.now
    }
  },
  
  // Approved by (for official reports)
  approvedBy: {
    userId: String,
    userName: String,
    timestamp: Date,
    signature: String
  },
  
  // Report format and delivery
  format: {
    type: String,
    enum: ['PDF', 'JSON', 'CSV', 'HTML'],
    default: 'PDF'
  },
  
  storage: {
    path: String,
    encrypted: {
      type: Boolean,
      default: true
    },
    retentionPeriod: Number // in days
  },
  
  // Distribution
  distribution: {
    recipients: [{
      email: String,
      role: String,
      notified: {
        type: Boolean,
        default: false
      },
      notificationDate: Date
    }],
    sharedExternally: {
      type: Boolean,
      default: false
    }
  }
}, {
  timestamps: true
});

// Indexes for efficient querying
complianceReportSchema.index({ reportType: 1, 'period.startDate': -1 });
complianceReportSchema.index({ 'status.overall': 1 });
complianceReportSchema.index({ 'generatedBy.userId': 1 });
complianceReportSchema.index({ 'requirements.standard': 1 });
complianceReportSchema.index({ 'findings.severity': 1 });

// Compound indexes
complianceReportSchema.index({ reportType: 1, 'period.startDate': -1, 'status.overall': 1 });

module.exports = mongoose.model('ComplianceReport', complianceReportSchema);